#!/usr/bin/env python
import argparse
import json
import sys
import os
import pygeons.ioconv
import pygeons.interface
import logging
  
def change_extension(f,ext):
  return '.'.join(f.split('.')[:-1] + [ext])

p = argparse.ArgumentParser()
p.add_argument('input_file',type=str,
               help='''date file. Can either be a PBO csv file, a PBO 
                       pos file, or a HDF5 file. The file type is 
                       inferred from the extension. ".hdf", ".h5", 
                       ".hdf5", ".he5" are interpretted as HDF5, 
                       ".pos" is interpretted as PBO pos, anything 
                       else is assumed to be a PBO csv file.''')
p.add_argument('sample_period',type=int,
               help='''sample period in days''')
p.add_argument('--output_file',type=str,
               help='''if not provided then the input file extension 
                       is removed and replaced with smooth.h5. The 
                       output file type is inferred from the 
                       extension. Currently, can only output to HDF5 
                       files or PBO csv files.''')
p.add_argument('-v','--verbose',action='count',default=0,
               help='''controls verbosity''')
p.add_argument('--start_date',type=str,
               help='''resample start date in YYYY-MM-DD''')
p.add_argument('--stop_date',type=str,
               help='''resample stop date in YYYY-MM-DD''')
p.add_argument('--cut_dates',nargs='+',type=str,
               help='''list of time discontinuities in YYYY-MM-DD. 
                       This date should be when the discontinuity is 
                       first observed''')
               
p = vars(p.parse_args())

# set logger
verbose = p.pop('verbose')
if verbose == 0:
  logging.basicConfig(level=logging.WARNING)
elif verbose == 1:
  logging.basicConfig(level=logging.INFO)
else:
  logging.basicConfig(level=logging.DEBUG)

input_file = p.pop('input_file')
output_file = p.pop('output_file')

# throw out any Nones and let the lower level functions determine the defaults
for k in p.keys():
  if p[k] is None:
    p.pop(k)

if output_file is None:
  output_file = change_extension(input_file,'downsample.h5')

data_dict = pygeons.ioconv.dict_from_hdf5(input_file)
out_dict = pygeons.interface.downsample(data_dict,**p)
pygeons.ioconv.hdf5_from_dict(output_file,out_dict)
