#!/usr/bin/env python
import argparse
import logging
from pygeons import *

def change_extension(f,ext):
  return '.'.join(f.split('.')[:-1] + [ext])

p = argparse.ArgumentParser(
  description='''Converts a text data file to an HDF5 file''')

p.add_argument(
  'input_file',type=str,metavar='STR',
  help='''input file name. This must be a text file''')

p.add_argument(
  'file_type',type=str,metavar='STR',
  choices=['pbopos','pbocsv','csv','tdecsv'],
  help='''Input file type''')

p.add_argument(
  '-o','--output_file',type=str,metavar='STR',
  help='''Output file name. If this is not provided then it is the 
          same as the input file name but the extension is removed 
          and replaced with "h5"''')

p.add_argument(
  '-v','--verbose',action='count',default=0,
  help='''controls verbosity''')
               
p = vars(p.parse_args())

# set logger
verbose = p.pop('verbose')
if verbose == 0:
  logging.basicConfig(level=logging.WARNING)
elif verbose == 1:
  logging.basicConfig(level=logging.INFO)
else:
  logging.basicConfig(level=logging.DEBUG)

input_file = p.pop('input_file')
output_file = p.pop('output_file')
file_type = p.pop('file_type')
if output_file is None:
  output_file = change_extension(input_file,'h5')

if file_type == 'csv':
  data_dict = dict_from_text(input_file,parse_csv)
elif file_type == 'pbocsv':
  data_dict = dict_from_text(input_file,parse_pbocsv)
elif file_type == 'tdecsv':
  data_dict = dict_from_text(input_file,parse_tdecsv)
elif file_type == 'pbopos':
  data_dict = dict_from_text(input_file,parse_pbopos)
    
hdf5_from_dict(output_file,data_dict)
