#!/usr/bin/env python
import argparse
import logging
from pygeons import *

def change_extension(f,ext):
  return '.'.join(f.split('.')[:-1] + [ext])

p = argparse.ArgumentParser(
  formatter_class=argparse.RawDescriptionHelpFormatter,
  description=
''' 
Converts a text data file to an HDF5 file

'''
)
p.add_argument('input_file',**GLOSSARY['input_file'])
p.add_argument('-f','--file_type',**GLOSSARY['file_type'])
p.add_argument('-o','--output_file',**GLOSSARY['output_file'])
p.add_argument('-v','--verbose',**GLOSSARY['verbose'])
p = vars(p.parse_args())

input_file = p.pop('input_file')
output_file = p.pop('output_file')
file_type = p.pop('file_type')
verbose = p.pop('verbose')
logging.basicConfig(level=30-10*verbose)

if output_file is None:
  output_file = change_extension(input_file,'h5')

data_dict = dict_from_text(input_file,file_type)
hdf5_from_dict(output_file,data_dict)
