#!/usr/bin/env python
import argparse
import json
import sys
from pygeons.io.convert import dict_from_hdf5
import pygeons.interface
import logging

p = argparse.ArgumentParser(
  description='''Runs the PyGeoNS Interactive Strain Viewer''')

p.add_argument(
  'xdiff_file',type=str,metavar='STR',
  help='''date file containing the x derivative of the vector field''')
p.add_argument(
  'ydiff_file',type=str,metavar='STR',
  help='''date file containing the y derivative of the vector field''')

p.add_argument(
  '-v','--verbose',action='count',default=0,
  help='''controls verbosity''')
  
p.add_argument('--resolution',type=str,metavar='STR')               
p.add_argument('--scale',type=float,metavar='FLOAT')
p.add_argument('--map_title',type=str,metavar='STR')
p.add_argument('--map_xlim',nargs=2,type=float,metavar='FLOAT')
p.add_argument('--map_ylim',nargs=2,type=float,metavar='FLOAT')
p.add_argument('--fontsize',type=float,metavar='FLOAT')
p.add_argument(
  '--break_lons',nargs='+',type=float,metavar='FLOAT',
  help='''Longitudes of the spatial discontinuity vertices''')

p.add_argument(
  '--break_lats',nargs='+',type=float,metavar='FLOAT',
  help='''Latitudes of the spatial discontinuity vertices''')

p.add_argument(
  '--break_conn',nargs='+',type=str,metavar='STR',
  help='''Connectivity of the spatial discontinuity vertices. This can 
          be one or multiple strings where each string contains the 
          vertex indices making up each discontinuity separated by a 
          '-'. For example, '0-1-2 3-4' indicates that there are two 
          discontinuties, one contains vertices 0, 1, and 2 and the 
          other contains vertices 3 and 4''')
               
p = vars(p.parse_args())

# set logger
verbose = p.pop('verbose')
if verbose == 0:
  logging.basicConfig(level=logging.WARNING)
elif verbose == 1:
  logging.basicConfig(level=logging.INFO)
else:
  logging.basicConfig(level=logging.DEBUG)

xdiff_file = p.pop('xdiff_file')
xdiff_dict = dict_from_hdf5(xdiff_file)
ydiff_file = p.pop('ydiff_file')
ydiff_dict = dict_from_hdf5(ydiff_file)

# throw out any Nones and let the lower level functions determine the defaults
for k in p.keys(): 
  if p[k] is None: 
    p.pop(k)

pygeons.interface.strain(xdiff_dict,ydiff_dict,**p)
